// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiHG20c33rLx5c3lFPcmBWfn2nWPf6xGU',
    appId: '1:1087366891314:web:1f148c706143782977b92b',
    messagingSenderId: '1087366891314',
    projectId: 'fir-tutorial-cff6a',
    authDomain: 'fir-tutorial-cff6a.firebaseapp.com',
    storageBucket: 'fir-tutorial-cff6a.firebasestorage.app',
    measurementId: 'G-E5LG8SDM0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXH8EqtUg55SaE-bT4qJUuUxGrZYK259U',
    appId: '1:594388494623:android:3878df1cfdce34259c682a',
    messagingSenderId: '594388494623',
    projectId: 'whatzapp-234bb',
    storageBucket: 'whatzapp-234bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSVwn-v4udc4GPTiRyL_17ZR8SPI0NC1M',
    appId: '1:594388494623:ios:895a73e46b3253df9c682a',
    messagingSenderId: '594388494623',
    projectId: 'whatzapp-234bb',
    storageBucket: 'whatzapp-234bb.firebasestorage.app',
    iosBundleId: 'com.example.wazzUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ2sTKkj7FLDppCqZiGFuEOTeX7v1yLQg',
    appId: '1:1087366891314:ios:c8ff6ebb2bed946277b92b',
    messagingSenderId: '1087366891314',
    projectId: 'fir-tutorial-cff6a',
    storageBucket: 'fir-tutorial-cff6a.firebasestorage.app',
    iosBundleId: 'com.example.wazzUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiHG20c33rLx5c3lFPcmBWfn2nWPf6xGU',
    appId: '1:1087366891314:web:ea30b4a14dbc6e6977b92b',
    messagingSenderId: '1087366891314',
    projectId: 'fir-tutorial-cff6a',
    authDomain: 'fir-tutorial-cff6a.firebaseapp.com',
    storageBucket: 'fir-tutorial-cff6a.firebasestorage.app',
    measurementId: 'G-XFPGD652T1',
  );

}